server:
  port: 5555

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "routes"

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

zuul:
  sensitive-headers:
    - Cookie, Authorization